import type { NextPage } from 'next';
import { GetServerSideProps } from 'next';
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react';
import StreakCard from '../components/streak-card/streak-card'
import TaskCard from '../components/task/task'
import styles from '../styles/Home.module.css';

export const getServerSideProps: GetServerSideProps = async (context) => {
  const res = await fetch(`https://jsonplaceholder.typicode.com/users/1/todos`)
  const data = await res.json()

  if (!data) {
    return {
      notFound: true,
    }
  }

  return {
    props: { 
      tasks: data
     }, // will be passed to the page component as props
  }
}


const Home: NextPage = ({tasks}: any) => {
  const [completedTasks, setCompletedTasks] = useState<number>(0);
  const [totalTasks, setTotalTasks] = useState<number>(0);
  const [unCompletedTasks, setUnCompletedTasks] = useState<number>(0);

  const hydrateTasks = (tasks: any[]) => {
    let completedTasks: any[] = [];
    let unCompletedTasks: any[] = [];

    tasks.forEach((task:any) => {
      if(task.completed){
        completedTasks.push(task);
        setCompletedTasks(completedTasks.length);
      }else{
        unCompletedTasks.push(task);
        setUnCompletedTasks(unCompletedTasks.length);
      }
    })
  }
  useEffect(() => {
    if(tasks){
      setTotalTasks(tasks.length);
      hydrateTasks(tasks);
    }
  }, [tasks])
  
  return (
    <div>
      <Head>
        <title>Task Management App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha512-SfTiTlX6kk+qitfevl/7LibUOeJWlt9rbyDn92a1DqWOw9vWG2MFoays0sgObmWazO5BQPiFucnnEAjpAB+/Sw==" crossOrigin="anonymous" referrerPolicy="no-referrer" />
      </Head>

      <main className={styles.main}>
        <div className={`${styles.sidebar}`}>
          <h1 className={`h1 text-light`}>User Name</h1>
        </div>
        <div className={styles.mainContent}>
          <div className='flex justify-between'>
            <div className='flex-1'>
              <span><i className="fa fa-bars" aria-hidden="true"></i></span>
            </div>
            <div className='flex-1 text-right'>
              <span className='p-1'><i className="fa fa-search" aria-hidden="true"></i></span>
              <span className='p-1'><i className="fa fa-bell-o" aria-hidden="true"></i></span>
            </div>
          </div>

          <div className={styles.welcomeText}>
            <h1 className={`h1 text-light`}>Whats up Michael!</h1>
          </div>

          <div className='flex'>
              <div className='flex-1 mr-1'>
                <StreakCard title='Uncompleted Tasks' percentage={((unCompletedTasks/ totalTasks) * 100)} numOfTasks={unCompletedTasks} color="#D103FC" />
              </div>
              <div className='flex-1 ml-1'>
                <StreakCard title='Completed Tasks' percentage={((completedTasks / totalTasks) * 100)} numOfTasks={completedTasks} color="#4F74FF" />
              </div>
          </div>

          <div>
            <p>Todays Tasks</p>
            {
              tasks && tasks.map((task: any) => {
                // return <div key={task.id}>
                //         <TaskCard task={task}/>
                //       </div>
                return <TaskCard key={task.id} task={task} />
              })
            }
          </div>

          <div className={styles.floatBtn}>
            <button>
              <i className="fa fa-plus" aria-hidden="true"></i>
            </button>
          </div>
        </div>
      </main>

    </div>
  )
}

export default Home
